'use strict';

const { URL } = require('url');
const { normalizeHeaders, getContentType } = require('./utils');
const { correlateTokens } = require('./tokenCorrelate');
const { getExtractorsForRecords } = require('./extractVars');

const SKIP_HEADERS = new Set([
  'content-length',
  'host',
  'connection',
  'accept-encoding',
  'transfer-encoding',
  'keep-alive',
  'proxy-connection',
  'te',
  'trailer',
  'upgrade',
  'expect',
  'cookie'
]);

function jsString(value) {
  return JSON.stringify(value == null ? '' : String(value));
}

function k6JsonSelector(jsonPath) {
  const raw = String(jsonPath || '').trim();
  if (!raw || raw === '$') return null;
  if (raw.startsWith('$.')) return raw.slice(2);
  if (raw.startsWith('$[')) return raw.slice(1);
  return raw;
}

function collectValidRecords(records) {
  const valid = [];
  const skipped = [];
  (records || []).forEach((record) => {
    const url = record && record.url;
    if (!url) {
      skipped.push({ record, reason: 'missing url' });
      return;
    }
    let parsedUrl;
    try {
      parsedUrl = new URL(String(url));
    } catch (e) {
      skipped.push({ record, reason: 'invalid url' });
      return;
    }
    if (parsedUrl.protocol !== 'http:' && parsedUrl.protocol !== 'https:') {
      skipped.push({ record, reason: 'unsupported protocol' });
      return;
    }
    valid.push({
      record,
      parsedUrl,
      protocol: parsedUrl.protocol.replace(':', ''),
      domain: parsedUrl.hostname,
      port: parsedUrl.port || (parsedUrl.protocol === 'https:' ? '443' : '80'),
      method: record.method ? String(record.method).toUpperCase() : 'GET'
    });
  });
  return { valid, skipped };
}

function filterHeaders(headers) {
  const out = {};
  Object.keys(headers || {}).forEach((key) => {
    if (SKIP_HEADERS.has(String(key).toLowerCase())) return;
    out[key] = headers[key];
  });
  return out;
}

function buildPlans(valid, options) {
  const manuals = getExtractorsForRecords(valid.map((item) => item.record && item.record.id));
  return correlateTokens(valid.map((item) => item.record), {
    edits: options && options.correlateEdits,
    manualExtractors: manuals,
    autoCorrelate: !options || options.correlateToken !== false
  });
}

function emitExtractors(extractors, resVar) {
  const lines = [];
  (extractors || []).forEach((ext) => {
    const name = ext.varName || 'extracted';
    if (ext.type === 'json' && ext.jsonPath) {
      const selector = k6JsonSelector(ext.jsonPath);
      if (selector) {
        lines.push(`  vars.${name} = ${resVar}.json(${jsString(selector)});`);
        return;
      }
      lines.push(`  try { vars.${name} = JSON.parse(${resVar}.body); } catch (e) { vars.${name} = null; }`);
      return;
    }
    if (ext.regex) {
      const source = ext.useHeaders
        ? `Object.entries(${resVar}.headers).map(([k,v]) => k + ': ' + v).join('\\n')`
        : `${resVar}.body`;
      lines.push(`  { const _m = (${source}).match(${jsString(ext.regex)}); vars.${name} = _m ? _m[1] : vars.${name}; }`);
      return;
    }
    if (ext.jsonPath) {
      const selector = k6JsonSelector(ext.jsonPath);
      if (selector) lines.push(`  vars.${name} = ${resVar}.json(${jsString(selector)});`);
    }
  });
  return lines;
}

function requestBodyForRecord(record, plan) {
  if (record.requestBodyBinary) return { body: null, note: 'binary body skipped' };
  const multipart = plan.multipart || record.multipart;
  if (multipart && ((multipart.files && multipart.files.length) || (multipart.fields && multipart.fields.length))) {
    return { body: null, note: 'multipart skipped — configure manually in k6' };
  }
  const headers = plan.headers || normalizeHeaders(record.requestHeaders || record.headers || {});
  const body = plan.body != null ? plan.body : (record.requestBody != null && record.requestBody !== ''
    ? String(record.requestBody)
    : String(record.body || ''));
  return { body: body || null, headers, contentType: getContentType(headers) };
}

function buildRequestUrl(item, plan) {
  const pathPart = plan.path || ((item.parsedUrl.pathname || '/') + item.parsedUrl.search);
  return `${item.protocol}://${item.domain}${item.port && item.port !== '80' && item.port !== '443' ? `:${item.port}` : ''}${pathPart}`;
}

function generateK6Script(records, options = {}) {
  if (!records || records.length === 0) {
    throw new Error('No records provided to generate k6 script');
  }
  const { valid, skipped } = collectValidRecords(records);
  if (!valid.length) {
    throw new Error('No valid HTTP records to export');
  }
  const threads = Math.min(Math.max(Number(options.threads) || 1, 1), 1000);
  const loops = Math.min(Math.max(Number(options.loops) || 1, 1), 10000);
  const rampTime = Math.max(Number(options.rampTime) || 0, 0);
  const plans = buildPlans(valid, options);
  const lines = [
    '// Generated by whistle.jmeter-exporter — run: k6 run script.js',
    "import http from 'k6/http';",
    "import { check, sleep } from 'k6';",
    '',
    'export const options = {',
    '  scenarios: {',
    '    main: {',
    "      executor: 'ramping-vus',",
    `      startVUs: 0,`,
    `      stages: [`,
    ...(rampTime > 0
      ? [`        { duration: '${rampTime}s', target: ${threads} },`, `        { duration: '1s', target: ${threads} },`]
      : [`        { duration: '1s', target: ${threads} },`]),
    `        { duration: '${Math.max(loops, 1)}s', target: ${threads} },`,
    '      ],',
    "      gracefulRampDown: '5s',",
    '    },',
    '  },',
    '  thresholds: {',
    "    http_req_failed: ['rate<0.05'],",
    "    http_req_duration: ['p(95)<2000'],",
    '  },',
    '};',
    '',
    'export default function () {',
    '  const vars = {};',
    ''
  ];

  if (skipped.length) {
    lines.splice(1, 0, `// Skipped ${skipped.length} record(s) (invalid URL or unsupported protocol)`);
  }

  valid.forEach((item, index) => {
    const plan = plans[index] || {};
    const record = item.record;
    const method = item.method;
    const headers = filterHeaders(plan.headers || normalizeHeaders(record.requestHeaders || record.headers || {}));
    const bodyInfo = requestBodyForRecord(record, plan);
    const url = buildRequestUrl(item, plan);
    const resVar = `res${index + 1}`;
    const label = `${method} ${url.split('?')[0]}`.slice(0, 120);

    lines.push(`  // ${index + 1}. ${label}`);
    if (bodyInfo.note) lines.push(`  // ${bodyInfo.note}`);

    const params = [`headers: ${JSON.stringify(headers)}`];
    if (bodyInfo.body != null && bodyInfo.body !== '') {
      params.push(`body: ${jsString(bodyInfo.body)}`);
    }
    const paramsObj = `{ ${params.join(', ')} }`;

    if (method === 'GET' || method === 'HEAD' || method === 'DELETE') {
      lines.push(`  const ${resVar} = http.${method.toLowerCase()}(${jsString(url)}, ${paramsObj});`);
    } else {
      lines.push(`  const ${resVar} = http.${method.toLowerCase()}(${jsString(url)}, ${paramsObj});`);
    }
    lines.push(`  check(${resVar}, { '${method} ok': (r) => r.status >= 200 && r.status < 400 });`);
    lines.push(...emitExtractors(plan.extractors, resVar));
    lines.push('  sleep(0.1);');
    lines.push('');
  });

  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

module.exports = {
  generateK6Script,
  k6JsonSelector,
  collectValidRecords
};
